[pytest]
addopts = --reruns 2 --reruns-delay 1 --html=reports/html_report.html --self-contained-html --alluredir=allure_reports
testpaths = testcases
markers =
    api: API automation tests
    regression: Regression tests